version: '3.9'
services:
  elasticsearch:
    image: elasticsearch:7.14.1
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: kibana:7.14.1
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
    ports:
      - 5601:5601

volumes:
  elasticsearch-data:
