# curl -X PUT "localhost:9200/shops" -H 'Content-Type: application/json' -d'
#{
#  "mappings": {
#    "properties": {
#      "geopoint": {
#        "type": "geo_point"
#      }
#    }
#  }
#}
#'
PUT localhost:9200/shops
Content-Type: application/json


{
  "mappings": {
    "properties": {
      "geopoint": {
        "type": "geo_point"
      }
    }
  }
}


###

